### PR TITLE
Minor corrections to 'modi' verb and '#' mention

### PR DESCRIPTION
**Pull request by RayZ0rr**
> Please follow these steps before submitting your PR:
>
> - [x] This PR targets the `next` branch and not `master`
> - [ ] If your PR is a work in progress, include [WIP] in its title
> - [x] Its commits' summaries are reasonably descriptive
> - [x] You've described what this PR addresses below
> - [x] You've included links to relevant issues, if any with `#issue_num`
> - [ ] You've deleted this template
>
> Thank you for contributing to rofi! <3

Add some mentions of `modi` in readme and mention of `#` as a modi separator

### CODE REVIEW

**Comment by DaveDavenport** [comment]
This seems incorrect..  You launch one mode, and you enable multiple modi.

**Comment by DaveDavenport** [comment]
The '#' is an exception for help with i3, it is mentioned in the manpage. I don't see why this should be added to the README.

**Comment by RayZ0rr** [comment]
> This seems incorrect.. You launch one mode, and you enable multiple modi.

The correction is to indicate that `mode` and `modi` will be used interchangeably so that the user won't be confused. Like here from README:
> To launch rofi directly in a certain mode, specify a mode with rofi -show <mode>. To show the run dialog

So, that users won't be confused by `mode`/`modi` terminology.

**Comment by RayZ0rr** [comment]
> The '#' is an exception for help with i3, it is mentioned in the manpage. I don't see why this should be added to the README.

Other than i3, this can also be useful for some sort of user-script utilities. In case someone misses it in the readme.

**Comment by DaveDavenport** [comment]
your correction is still wrong, `rofi -show <mode>` takes one mode, not multiple.
`rofi -show <modi>`  (that you even indicates is  "modes", so the fact it is multiple was not confusing) is not valid!

For lists comma is a logical separator, the fact we support `#` is just to workaround i3 weirdness, I see no reason why somebody should use this in a script.   I also find 'some sort of user script' no clear explanation why it has added value as it has no example or more information.

**Comment by RayZ0rr** [comment]
> your correction is still wrong, `rofi -show <mode>` takes one mode, not multiple. `rofi -show <modi>` (that you even indicates is "modes", so the fact it is multiple was not confusing) is not valid!

There was a small typo. I have corrected it. However, it should be clear from what I said before what I was trying to achieve.

> The correction is to indicate that mode and modi will be used interchangeably so that the user won't be confused. Like here from README

Also, I know that it takes one argument only.
> `rofi -show <mode>` takes one mode, not multiple

If the typo was causing confusion then I have fixed it. There's no other location I have mentioned it takes multiple arguments.

> For lists comma is a logical separator, the fact we support `#` is just to workaround i3 weirdness, I see no reason why somebody should use this in a script. I also find 'some sort of user script' no clear explanation why it has added value as it has no example or more information.

This may or may not be added. It's rather trivial I guess

**Comment by DaveDavenport** [comment]
I don't understand the miscommunication,  this edit makes it worse imho. 

I am not sure how to explain,

The show command takes one 'mode' name, not multiple. saying `rofi -show modi` is therefor wrong!

mode -> single
modi -> plural

**Comment by DaveDavenport** [comment]
> This may or may not be added. It's rather trivial I guess

I want a good reason why it should be added, I prefer not to give superfluous information in the readme. It is mentioned in the manpage, the only reason to use the illogical # as list separator is for i3 users and it explicitly references this..

As mention before, 'some sort of user script' does not provide me with any detail/explanation  to go on. If there is a strong reason to include it in the readme, please tell me.

**Comment by DaveDavenport** [comment]
Should we change 'modi' to 'modes' to make it clearer?

(we should update all documentation then to keep it consistent)

**Comment by DaveDavenport** [comment]
changed the modi -> modes.

**Comment by RayZ0rr** [comment]
Hey Dave, I'm sorry for being late. My laptop is at repair shop.

I thought `modi` was your special term for mode. I didn't know you meant plural of mode. That is why all this confusion happened.

Also, won't the commit break existing configurations? Is that necessary? I'm sorry because I am kinda responsible for this. I just wanted to clarify the readme a bit more

**Comment by DaveDavenport** [comment]
No, its backward compatible. The old options are aliased to the new one.
Your confusion was a good indication it was not clear. Hopefully it is better now.

**Comment by RayZ0rr** [comment]
Okay, so they won't be deprecated soon? 

Maybe add a note somewhere on interchangeability between modes and modi? This is so that old users won't be confused when reading upon it in README or man.

Also, close this PR?

Once again thanks for your hardwork.

**Comment by DaveDavenport** [comment]
yeah, `switchers` also still works and that been deprecated ages ago.

**Pull request closed without merging**
