### PR TITLE
Add Issue and PR Templates

### PR DESCRIPTION
**Pull request by mustaqimM**
Inspiration from:
 https://github.com/hlissner/doom-emacs/tree/develop/.github/ISSUE_TEMPLATE

Here's how it looks:
https://github.com/hlissner/doom-emacs/issues/new/choose

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Very nice!.
I prefer not to have a 'how to' one, as I want to keep issue tracker for issues
(and feature requests, even that I would rather have split).

Thanks!

**Comment by mustaqimM** [comment]
okay np, so I should get rid of the Question and Feature Requests templates?

**Comment by DaveDavenport** [comment]
lets keep the freature request, just remove the question one.

Thanks!

**Comment by DaveDavenport** [comment]
Perfect. Thanks!!!

**Pull request merged**
