### PR TITLE
workaround for #303

### PR DESCRIPTION
**Pull request by nick87720z**
Workaround for issue #303 
Subpixel rendering may be disabled by some clip paths or when text itself is clipped. I tested only with quadrangular path. Any non orthogonal line is enough to make subpixel noop.
Workaround here is to use intermediate image surface, so that no need to disable clipping.

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Any idea what the performance impact is of this patch?

**Comment by DaveDavenport** [comment]
Got around 2% drop. Not bad.

**Comment by nick87720z** [comment]
I did perf for various approaches for text rendering. Pango seems to be heaviest of all graphics, comparing to simple color fills and lines. It doesn't even honor tolerance option (not sure is it good or bad).

There is minimal example, I used for drawing.
https://gist.github.com/nick87720z/53a1c952d479b67a7f2b096a88deed81

Preserving intermediate surface/painter makes no difference for me.
Recording surface gives little speedup comparing to image.
This allowes to get rid of extent calc, but it seems that final layout draw call needs it anyway, so no diff.
cairo toy api (cairo_show_text) gave 3.5 .. 4.0x perf boost. If course it would lack pango layout support. And it gives extents only for painted area, not logical.

**Comment by DaveDavenport** [comment]
thanks.

**Pull request merged**
