### PR TITLE
Add a fast fuzzy filter to avoid g_regex_match in SORT_FUZZY mode

### PR DESCRIPTION
**Pull request by MaskRay**
Based on #1173

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Is this utf-8 compatible?

**Comment by MaskRay** [comment]
Is there a way typing case-significant Unicode? :) (#483)

**Comment by DaveDavenport** [comment]
How is what you can enter relevant for sorting?  the entered value is not sorted. :smile:

**Comment by MaskRay** [comment]
Made it utf-8 clean

**Comment by DaveDavenport** [comment]
I see for fuzzy match you do not use `mode_token_match ( t->state->sw, t->state->tokens, i );` anymore?   This will break matching for different modi.

**Comment by MaskRay** [comment]
I don't know how to run rofi under cgdb, so it is a bit difficult for me to understand the logic. `mode_token_match` appears to call g_regex_match, which may be slow when running in dmenu mode on a collection of thousands of lines.

If `mode_token_match` is still significant, we can run `mode_token_match` after the filter.

**Comment by DaveDavenport** [comment]
`If mode_token_match is still significant, we can run mode_token_match after the filter.`

That would not produce the same result in all cases.

**Comment by MaskRay** [comment]
> `If mode_token_match is still significant, we can run mode_token_match after the filter.`
> 
> That would not produce the same result in all cases.

Why? Can you elaborate on what `mode_token_match` does?

**Comment by DaveDavenport** [comment]
`mode_token_match` is forwarded to the active mode, that uses this to match against (possibly) invisible fields.

In f.e. drun you can select what fields to match/display independently.
In f.e. dmenu you can set an invisible item to match against (on request).
in rofi-blezz this is used to override the matching .

**Comment by MaskRay** [comment]
> And as mentioned in other MR, sorting and matching are separate items in rofi. This will break that.

I think I simply don't have enough context to fix the issues. For me, I just need a somewhat usable fuzzy matching algorithm.... don't want to deal with separate matching and sorting which does not fit well to me. I'll close this PR then.

**Pull request closed without merging**
