### PR TITLE
Fix Travis CI builds

### PR DESCRIPTION
**Pull request by devopsdeluxe**
Work towards getting rofi's Travis CI builds passing again.

* Add libjpeg-dev to apt packages list

### CODE REVIEW

**Comment by devopsdeluxe** [comment]
This is ready for review!

**Comment by DaveDavenport** [comment]
Very nice, thanks.

Might be nice idea to do both a meson and autotools build.

**Comment by devopsdeluxe** [comment]
> Might be nice idea to do both a meson and autotools build.

I'll read up on autotools and get a job for it into this MR.

Pardon my tangent here:

I think implementing https://github.com/davatorium/rofi/pull/920#issuecomment-550972864 in this MR wouldn't be a bad idea either, since I'm already doing a little cleanup...

Also releated to this MR: https://codecov.io/gh/davatorium/rofi/commits Codecov hasn't picked anything up in ~7 months. Since I'm touching up `.travis-ci.yml` would it be worth looking into getting that working again?

**Comment by DaveDavenport** [comment]
> I think implementing [#920 (comment)](https://github.com/davatorium/rofi/pull/920#issuecomment-550972864) in this MR wouldn't be a bad idea either, since I'm already doing a little cleanup...

I don't think pulling in unrelated things in a MR is wise thing to do.

Codecov stopped working, because travis stopped working. It should work again once travis is up and running.

**Comment by DaveDavenport** [comment]
For make this should do:
```
mkdir buildmake
cd buildmake
./configure 
make
make distcheck
```
Last one is used for releases, so good to check.

**Comment by devopsdeluxe** [comment]
> Can we provide the created tar as a artifact?

Yes!

https://docs.travis-ci.com/user/deployment/releases/

**Comment by DaveDavenport** [comment]
Thanks for all your work. My internet modem died, so have to do everything mobile, once it is fixed I will review it!

**Comment by DaveDavenport** [comment]
On the travis branch I pushed some fixes to this MR.    IT now passes the checks.

**Comment by DaveDavenport** [comment]
https://travis-ci.org/github/davatorium/rofi/builds/681151857

**Pull request merged**
