### PR TITLE
Add wezterm to rofi-sensible-terminal

### PR DESCRIPTION
**Pull request by yutkat**
I would like to add wezterm as it is a popular terminal these days and has many users.

https://github.com/wez/wezterm

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Can you also update the relevant manpage?

**Comment by yutkat** [comment]
Updated. Please check it.

**Comment by DaveDavenport** [comment]
Great! thanks.

**Comment by DaveDavenport** [comment]
hope this worked, github been throwing errors.

**Pull request merged**
