### PR TITLE
Add cursor property

### PR DESCRIPTION
**Pull request by TonCherAmi**
This pull request adds a new theme property `cursor` that allows specifying the type of mouse cursor that is set when the widget is hovered. It can be set to either `default`, `pointer`, or `text`:

- `default` is the default arrow cursor
- `pointer` could be used for clickable areas:
image
- `text` could be used for input fields:
image

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Nice. 
For me the textbox does not work and the side-bar buttons are not changed.
I wonder if we should make it  a property on the widget itself.

**Comment by TonCherAmi** [comment]
> For me the textbox does not work and the side-bar buttons are not changed.

Huh, interesting.. Could you please share your config?

> I wonder if we should make it a property on the widget itself.

Yeah, I guess that would be ideal and I would personally prefer it that way, although it would take more effort to implement it that way and I'm not sure how useful it would end up being really.

**Comment by TonCherAmi** [comment]
Actually, it doesn't look that difficult to do, I'm going to give it a shot.

**Comment by DaveDavenport** [comment]
I ran it with -no-config. 
```rofi  -no-config -show run -sidebar-mode```

**Comment by TonCherAmi** [comment]
> I ran it with -no-config.
> `rofi -no-config -show run -sidebar-mode`

Yep, the sidebar buttons do not work. However the input box seems fine on my system. I think the issue might be that the cursor name for the I-beam on yours is not in the array. I'll try searching for some more alternative names, they seem to vary from theme to theme so it's a bit difficult to get them right.

**Comment by DaveDavenport** [comment]
I never set cursor themes anymore..

(long long long ago I did write a small ui to select them, gcursor, but that got absorbed into gnome settings at some point (and removed again)).

**Comment by TonCherAmi** [comment]
> I never set cursor themes anymore..

I think it's not cursor themes specifically, but rather GTK themes in general.

I've mostly got widget properties working, though there's a small problem with the recently added `-hover-select` option since it relies on the fact that `listview_element_motion_notify` is called conditionally and we now must call it unconditionally so that the cursor is updated for every widget. How do you feel about removing that option and making selection on hover the default behavior?

**Comment by DaveDavenport** [comment]
no direct feeling..  don't use mouse with rofi myself. Will give it some thoughts.

**Comment by TonCherAmi** [comment]
> no direct feeling.. don't use mouse with rofi myself. Will give it some thoughts.

Nevermind.. We can just check the settings inside the handler, no need to remove it.

**Comment by DaveDavenport** [comment]
Looks good.

**Comment by DaveDavenport** [comment]
thanks.`

**Pull request merged**
